export const MockList = [
  'abc_test_def',
  'TestRandom1',
  'another-test23',
  'thisIs_test4',
  'testxyzabc_Test',
  'Ghi_test1jktest2ltest3',
  'lmntestop',
  'uv_test_wxyz',
  'test123abc',
  'opqtestrst',
  'word_with_test',
  'thetestinmiddle',
  'testStartWithTest',
  'endwithtest',
  'more_test_here',
  'A_test_bc_test',
  'randteststr',
  'sometesttxt',
  'stillteston6',
  'yet_another_test',
] as const;
